### ISSUE TITLE
Critical Issue - Deployment not working on Mozilla Firefox

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#11]
The website is working fine on Mozilla Firefox, but once the deployment configuration is done, it crashes on the logs page, while the deployment is working in the background. After the site has been deployed the page comes back live again.

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by Man-Jain** [comment]
![Screenshot 2021-07-16 at 21-11-55 ArGo - Your decentralized Hosting and Storage Partner](https://user-images.githubusercontent.com/12700384/125973686-24428425-851f-4aad-bda7-f5300ae4cf1d.png)

**Comment by rekpero** [comment]
@Man-Jain Please check if it's working now! We fixed it

**Comment by Man-Jain** [comment]
Yes, Working for me :+1:

**Comment by rekpero** [comment]
Closing this issue as this is fixed 👍
