### ISSUE TITLE
Critical Issue - The website isn't deploying from choosen branch

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#12]
On deploying a private project from an org, even though a branch is chosen argo doesn't deploy the branch and instead deploys the default branch. 

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by Man-Jain** [comment]
Main branch was deployed even though a different branch was selected https://sodgeklwhpvkm5f6jhof2cu2ewygozgjevu5c5suguukxecntzeq.arweave.net/k4ZiKXY76qZ0vkncXQqaJbBnZMkladF2VDUoq5BNnkk/#/

**Comment by rekpero** [comment]
@Man-Jain Please check if it's working now! We fixed it

**Comment by Man-Jain** [comment]
Yes, Working for me :+1:

**Comment by rekpero** [comment]
Closing this issue as this is fixed 👍
