### ISSUE TITLE
Low - Should network name to switch to as `unknown`

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#14]
Shows `unknown` as the network name if connected to some unknown chain and also Instead of Matic Mainnet - `unknown`

![Screenshot 2021-07-16 at 21-21-09 ArGo - Your decentralized Hosting and Storage Partner](https://user-images.githubusercontent.com/12700384/125981397-faa7bd44-15c5-497b-b988-962e29cdc29b.png)

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by rekpero** [comment]
@Man-Jain Please check if it's working now! We fixed it

**Comment by Man-Jain** [comment]
Yes, Working for me :+1:

**Comment by rekpero** [comment]
Closing this issue as this is fixed 👍
