### ISSUE TITLE
High - Fetches the wallet/token allowance details on any network (not essential to be connected to matic testnet)

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#15]
Shows the wallet details and DAI allowance status even on dismissing the wallet connection error for unsupported chain, and also when connected to any other chain than Matic Testnet. 

![Screenshot 2021-07-16 at 21-22-52 ArGo - Your decentralized Hosting and Storage Partner](https://user-images.githubusercontent.com/12700384/125982064-20313d8e-c7db-4c72-ae7e-9e2d2fcdf29f.png)

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by Man-Jain** [comment]
Yes, Working for me :+1:

**Comment by rekpero** [comment]
Closing this issue as this is fixed 👍
