### ISSUE TITLE
Low - The `Visit Site` button not coming on a deployed project

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#16]
![Screenshot 2021-07-16 at 22-32-02 ArGo - Your decentralized Hosting and Storage Partner](https://user-images.githubusercontent.com/12700384/125983630-e923aa2d-b141-430e-ad4c-38afd3055c3f.png)

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by rekpero** [comment]
@Man-Jain Please check if it's working now! We fixed it

**Comment by Man-Jain** [comment]
Yes, Working for me :+1:

**Comment by rekpero** [comment]
Closing this as this is fixed 👍
