### ISSUE TITLE
Critical - Send Invite not working for some unknown reason

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#17]
Sending invite for an oraganization member not working, 

Also it doesn't show any popup or confirmation of whether email was sent or not. 

Can also send invite unlimited number of times. 

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by rekpero** [comment]
@Man-Jain Please check if it's working now! We fixed it

**Comment by Man-Jain** [comment]
Yes, Working for me :+1:

**Comment by rekpero** [comment]
Closing this issue as this is fixed 👍
