### ISSUE TITLE
Low - No indication on project cards of whether they can be clicked.

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#19]
There is no on hover animation or styling that might indicate that the project cards are clickable and we can see more information about project after that.

![Screenshot 2021-07-18 at 15-49-54 ArGo - Your decentralized Hosting and Storage Partner](https://user-images.githubusercontent.com/12700384/126063712-09b934ca-0bcd-4fb2-9d7a-b33f5fdf271c.png)

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by izrake** [comment]
@rekpero any updates on this?

**Comment by rekpero** [comment]
Release with V2.3
