### ISSUE TITLE
Low - No need to show all the decimal places for amounts and allowance

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#20]
Can round the decimal places for all the amounts. Will make the page look much neater.

![Screenshot 2021-07-18 at 15-53-04 ArGo - Your decentralized Hosting and Storage Partner](https://user-images.githubusercontent.com/12700384/126063795-d31f6ca8-4443-4b41-8d8d-79dce5d2cd89.png)

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by izrake** [comment]
Thank you for raising the bug. @rekpero I believe this can be done easily by showing 5 numbers after decimals and rest can be viewed using tooltip.

**Comment by rekpero** [comment]
Fixed with release V2.3
