### ISSUE TITLE
Low - On adding wallet to new organization it swtiches to the previous organization

### ISSUE THREAD

**Issue by Man-Jain** [argoapp-live/argo-bounty-issue#21]
Steps to reproduce- 

1. Create a new organization
2. Add wallet and  click on `Save` wallet
3. It will switch to the previous organization.

Wallet Address - 0x4Db928f96c8b6581a79557B269D9AD35935D3601

**Comment by izrake** [comment]
Thank you for raising the BUG, the team has fixed it. Please take a look and provide us your feedback.

**Comment by rekpero** [comment]
Fixed with release V2.3
